version: '3.8'

services:
  sql-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Streamlit port
      - "8000:8000"  # FastAPI port
    volumes:
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s