apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-chatbot
  labels:
    app: sql-chatbot
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sql-chatbot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sql-chatbot
        environment: production
    spec:
      containers:
      - name: sql-chatbot
        image: ${ACR_REGISTRY}/${DOCKER_IMAGE}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: frontend
        - containerPort: 8000
          name: backend
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sql-chatbot-secrets
              key: openai-api-key
        - name: DB_TYPE
          value: "sqlite"
        - name: DB_NAME
          value: "/app/data/sql_chatbot.db"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: API_URL
          value: "http://localhost:8000"
        - name: FRONTEND_HOST
          value: "0.0.0.0"
        - name: FRONTEND_PORT
          value: "5000"
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: sql-chatbot-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-chatbot-pvc
  labels:
    app: sql-chatbot
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: sql-chatbot-secrets
  labels:
    app: sql-chatbot
    environment: production
type: Opaque
data:
  openai-api-key: ${OPENAI_API_KEY_BASE64}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sql-chatbot-hpa
  labels:
    app: sql-chatbot
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sql-chatbot
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80